defmodule Shroud.Repo.Migrations.AddPostRefs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:post_refs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :post_id, :uuid, null: false
      add :visibility, :text, null: false
      add :posted_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :author_id,
          references(:users,
            column: :id,
            name: "post_refs_author_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:post_refs, [:post_id], name: "post_refs_unique_post_index")
  end

  def down do
    drop constraint(:post_refs, "post_refs_author_id_fkey")

    drop_if_exists unique_index(:post_refs, [:post_id], name: "post_refs_unique_post_index")

    drop table(:post_refs)
  end
end
