defmodule Shroud.Repo.Migrations.CreateGlobalTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audience_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :audience_id, :text, null: false
      add :wrapped_group_key, :text, null: false
      add :ephemeral_public_key, :text, null: false
      add :iv, :text, null: false
      add :generation, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id, :uuid, null: false
      add :member_id, :uuid, null: false
    end

    create unique_index(:audience_members, [:owner_id, :audience_id, :member_id, :generation],
             name: "audience_members_unique_membership_index"
           )

    create table(:credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :credential_id, :text, null: false
      add :cose_key, :binary, null: false
      add :sign_count, :bigint, default: 0
      add :label, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid, null: false
    end

    create unique_index(:credentials, [:credential_id],
             name: "credentials_unique_credential_id_index"
           )

    create table(:feed_edges, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :profile_updated_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :viewer_id, :uuid, null: false
      add :owner_id, :uuid, null: false
    end

    create unique_index(:feed_edges, [:viewer_id, :owner_id],
             name: "feed_edges_unique_edge_index"
           )

    create table(:key_wraps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :wrapped_key, :text, null: false
      add :iv, :text, null: false
      add :kdf_salt, :text
      add :kdf_iterations, :bigint
      add :credential_id, :text
      add :label, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid, null: false
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:audience_members) do
      modify :owner_id,
             references(:users,
               column: :id,
               name: "audience_members_owner_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :member_id,
             references(:users,
               column: :id,
               name: "audience_members_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:credentials) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "credentials_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:feed_edges) do
      modify :viewer_id,
             references(:users,
               column: :id,
               name: "feed_edges_viewer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :owner_id,
             references(:users,
               column: :id,
               name: "feed_edges_owner_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:key_wraps) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "key_wraps_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:users) do
      add :handle, :text, null: false
      add :display_hint, :text
      add :public_key, :text
      add :shredded_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:handle], name: "users_unique_handle_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:handle], name: "users_unique_handle_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :shredded_at
      remove :public_key
      remove :display_hint
      remove :handle
    end

    drop constraint(:key_wraps, "key_wraps_user_id_fkey")

    alter table(:key_wraps) do
      modify :user_id, :uuid
    end

    drop constraint(:feed_edges, "feed_edges_owner_id_fkey")

    drop constraint(:feed_edges, "feed_edges_viewer_id_fkey")

    alter table(:feed_edges) do
      modify :owner_id, :uuid
      modify :viewer_id, :uuid
    end

    drop constraint(:credentials, "credentials_user_id_fkey")

    alter table(:credentials) do
      modify :user_id, :uuid
    end

    drop constraint(:audience_members, "audience_members_member_id_fkey")

    drop constraint(:audience_members, "audience_members_owner_id_fkey")

    alter table(:audience_members) do
      modify :member_id, :uuid
      modify :owner_id, :uuid
    end

    drop table(:users)

    drop table(:key_wraps)

    drop_if_exists unique_index(:feed_edges, [:viewer_id, :owner_id],
                     name: "feed_edges_unique_edge_index"
                   )

    drop table(:feed_edges)

    drop_if_exists unique_index(:credentials, [:credential_id],
                     name: "credentials_unique_credential_id_index"
                   )

    drop table(:credentials)

    drop_if_exists unique_index(
                     :audience_members,
                     [:owner_id, :audience_id, :member_id, :generation],
                     name: "audience_members_unique_membership_index"
                   )

    drop table(:audience_members)
  end
end
